<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Ticket PDF</title>
  <style>
    @page { margin: 0; }
    body {
      font-family: 'DejaVu Sans', sans-serif;
      background: url('{{ public_path("images/ticket-bg.jpg") }}') no-repeat center center;
      background-size: cover;
      color: #2c3e50;
      padding: 50px;
    }
    .container {
      background-color: rgba(255, 255, 255, 0.9);
      padding: 30px;
      border-radius: 8px;
    }
    .header {
      text-align: center;
      font-size: 24px;
      font-weight: bold;
    }
    .details {
      margin-top: 30px;
    }
    .details p {
      margin: 4px 0;
    }
    .qr {
      text-align: center;
      margin-top: 30px;
    }
    .footer {
      text-align: center;
      font-size: 10px;
      margin-top: 40px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">{{ $ticket->event->name }}</div>
    <div class="details">
      <p><strong>Date:</strong> {{ $ticket->event->date->format('F j, Y \a\t g:i A') }}</p>
      <p><strong>Location:</strong> {{ $ticket->event->location }}</p>
      <p><strong>Ticket #:</strong> {{ $ticket->id }}</p>
      <p><strong>Type:</strong> Standard</p>
      {{-- <p><strong>Price:</strong> ${{ number_format($ticket->amount, 2) / 100 }}</p> --}}
      <p><strong>Status:</strong> {{ $ticket->status }}</p>
      <p><strong>Purchased:</strong> {{ $ticket->purchased_at }}</p>
    </div>

    @if($qrCode)
      <div class="qr">
        <img src="data:image/png;base64,{{ base64_encode($qrCode) }}" width="100" alt="QR Code">
        <p style="font-size: 11px; color: #666;">Scan this at the entrance</p>
      </div>
    @endif

    <div class="footer">
      Generated by TicketHub – support@tickethub.com
    </div>
  </div>
</body>
</html>
